### ISSUE TITLE
Gray-Scott split demo raises error when `export`ing data

### ISSUE THREAD

**Issue by ddundo** [mesh-adaptation/goalie#250]
```
Traceback (most recent call last):
  File "/home/firedrake/firedrake/src/goalie/demos/gray_scott_split.py", line 147, in <module>
    solutions.export(
  File "/home/firedrake/firedrake/src/goalie/goalie/function_data.py", line 200, in export
    self._export_vtk(output_fpath, export_field_types, initial_condition)
  File "/home/firedrake/firedrake/src/goalie/goalie/function_data.py", line 255, in _export_vtk
    outfile.write(*fs, time=time)
  File "petsc4py/PETSc/Log.pyx", line 188, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 189, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/firedrake/firedrake/src/firedrake/firedrake/output/vtk_output.py", line 653, in write
    vtu = self._write_vtu(*functions)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/firedrake/firedrake/src/firedrake/firedrake/output/vtk_output.py", line 519, in _write_vtu
    raise ValueError("Writing different set of functions")
ValueError: Writing different set of functions
```

**Comment by ddundo** [comment]
The reason is quite silly... The order of functions is not the same when we are saving initial conditions and when saving solutions:
```
('a_forward', 'a_adjoint', 'b_forward', 'b_adjoint')
('a_forward', 'b_forward', 'a_adjoint', 'b_adjoint')
```

Maybe worth opening a PR to Firedrake instead? Labelling as "discuss" for tomorrow
